import Head from 'next/head';
import TodoList from '../components/TodoList'; // Adjust the path if necessary

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Todo-List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-gradient-to-b from-[#2b37acbe] to-[#15162c]">
        <div className="container flex flex-col items-center justify-start gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(172,60%,50%)]">Todo-List</span>
          </h1>
          <TodoList />
        </div>
      </main>
    </>
  );
};

export default Home;
